// Generated by 'unplugin-auto-import'
export {}
declare global {
  const ElMeassage: typeof import('element-plus/es')['ElMeassage']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
}
